SimplyForum/Areas/Admin/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Category;

namespace SimplyForum.Areas.Admin.Controllers
{
    public class ReportController : AdminController
    {
        private readonly IPostReportService postReportService;

        public ReportController(IPostReportService _postReportService)
        {
            postReportService = _postReportService;
        }

        public async Task<IActionResult> All()
        {
            var model = await postReportService.GetAllPostReportsAsync();
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid postReportId)
        {
            await postReportService.DeletePostReportAsync(postReportId);
            return RedirectToAction(nameof(All));
        }
    }
}

SimplyForum/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Community;
using SimplyForum.Core.Models.Post;
using SimplyForum.Core.Services;
using SimplyForum.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICommentService commentService;
        private readonly ILikeService likeService;
        private readonly IPostReportService postReportService;

        public PostController(IPostService _postService, 
            ICommentService _commentService, 
            ILikeService _likeService,
            IPostReportService _postReportService)
        {
            postService = _postService;
            commentService = _commentService;
            likeService = _likeService;
            postReportService = _postReportService;
        }


        [HttpGet]
        public IActionResult Add(Guid id)
        {
            ViewData["PostType"] = "default";
            var model = new AddPostModel()
            {
                CommunityId = id
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Add(AddPostModel model)
        {
            model.AuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            if (model.Description != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "default";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddDefaultPostAsync(model);
                }
            }
            else if (model.Image != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "image";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddImagePostAsync(model);
                }
            }
            else if (model.Url != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "url";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddUrlPostAsync(model);
                }
            }

            return RedirectToAction("Details", "Community", new { communityId = model.CommunityId });
        }


        public async Task<IActionResult> Details(Guid postId)
        {
            ViewBag.userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            var model = await postService.GetPostDetailsAsync(postId);
            model.LikeCountModel = await likeService.GetReactionsByPostIdAsync(postId);
            model.Comments = await commentService.GetAllPostCommentsAsync(postId);
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid postId, Guid communityId)
        {
            var currentAuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            var actualAuthorId = await postService.GetPostAuthorId(postId);

            if (actualAuthorId != currentAuthorId && !User.IsInRole("Administrator"))
            {
                return Forbid();
            }

            await likeService.DeleteAllPostReactions(postId);
            await commentService.DeleteAllPostComments(postId);
            await postReportService.DeleteAllPostReports(postId);
            await postService.DeletePostAsync(postId);

            return RedirectToAction("Details", "Community", new { communityId = communityId });
        }
    }
}

SimplyForum/Areas/Admin/Views/Report/All.cshtml
@using SimplyForum.Core.Models.PostReport
@model ICollection<PostReportModel>
@{
    ViewBag.Title = "All reports";
}

@if(Model.Any() && Model != null)
{
    <h2 class="text-center">@ViewBag.Title</h2>
    <hr />
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <div class="card mt-2 border-primary align-content-center">
            @foreach (var postReport in Model)
            {
                <div class="card-body">
                    @{
                        var base64 = Convert.ToBase64String(postReport.User.ProfilePicture);
                        var imgSrc = String.Format($"data:image/gif;base64,{base64}");
                    }
                    <img src="@imgSrc" class="rounded-circle" width="40" height="40" />
                    <h3>@postReport.User.UserName</h3>
                    <h4>@postReport.Type.ToString()</h4>
                    <p>
                        @postReport.Description
                    </p>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Details","Post",new {postId = postReport.PostId})'">Details</button>
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete","Report",new {postReportId = postReport.Id})'">Delete report</button>
                </div>
            }
            <div class="card-footer">
            </div>
        </div>
    </div>
}
else
{
    <h2 class="text-center">There are no reports yet!</h2>
    <hr />
}