SimplyForum/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Category;

namespace SimplyForum.Areas.Admin.Controllers
{
    public class CategoryController : AdminController
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService _categoryService)
        {
            categoryService = _categoryService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddCategoryModel model = new AddCategoryModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCategoryModel model)
        {
            if(model.Type == null || model.Type.Length < 3 || model.Type.Length > 50)
            {
                return View(model);      
            }

            if(await categoryService.IsUniqueAsync(model.Type))
            {
                return View(model);
            }

            await categoryService.AddCategoryAsync(model);
            return RedirectToAction("Index", "Admin", new { area = "Admin" });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid categoryId)
        {
            var model = await categoryService.GetCategoryByIdAsync(categoryId);

            if(model.Type == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryModel model)
        {
            if (model.Type == null || model.Type.Length < 3 || model.Type.Length > 50)
            {
                return View(model);
            }

            if (await categoryService.IsUniqueAsync(model.Type))
            {
                return View(model);
            }

            await categoryService.EditCategoryAsync(model);
            return RedirectToAction("Index", "Admin", new { area = "Admin" });
        }

        public async Task<IActionResult> All()
        {
            var model = await categoryService.GetAllCategoriesAsync();

            return View(model);
        }
    }
}

SimplyForum/Areas/Admin/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Category;

namespace SimplyForum.Areas.Admin.Controllers
{
    public class ReportController : AdminController
    {
        private readonly IPostReportService postReportService;

        public ReportController(IPostReportService _postReportService)
        {
            postReportService = _postReportService;
        }

        public async Task<IActionResult> All()
        {
            var model = await postReportService.GetAllPostReportsAsync();
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid postReportId)
        {
            await postReportService.DeletePostReportAsync(postReportId);
            return RedirectToAction(nameof(All));
        }
    }
}

SimplyForum/Controllers/CommunityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Community;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class CommunityController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly ICommunityService communityService;
        private readonly IPostService postService;
        private readonly ILikeService likeService;

        public CommunityController(ICategoryService _categoryService,
            ICommunityService _communityService,
            IPostService _postservice,
            ILikeService _likeService)
        {
            categoryService = _categoryService;
            communityService = _communityService;
            postService = _postservice;
            likeService = _likeService;
        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AddCommunityModel()
            {
                CommunityCategories = await categoryService.GetAllCategoriesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCommunityModel model)
        {
            if (await communityService.IsCommunityNameUniqueAsync(model.Name))
            {
                ModelState.AddModelError("Name", "Community name is already used!");
                model.CommunityCategories.AddRange(await categoryService.GetAllCategoriesAsync());
                return View(model);
            }

            if (!ModelState.IsValid) {
                model.CommunityCategories.AddRange(await categoryService.GetAllCategoriesAsync());
                return View(model);
            }

            try
            {
                string authorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

                await communityService.AddCommunityAsync(model, authorId!);
                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Something went wrong!");
                model.CommunityCategories.AddRange(await categoryService.GetAllCategoriesAsync());
                return View(model);
            }
        }


        public async Task<IActionResult> All()
        {
            var model = await communityService.GetAllCommunitiesAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid communityId)
        {
            try
            {
                var model = await communityService.GetCommunityDetailsAsync(communityId);
                model.Posts = await postService.GetAllCommunityPostsAsync(communityId);
                foreach (var post in model.Posts)
                {
                    post.LikeCountModel = await likeService.GetReactionsByPostIdAsync(post.Id);
                }
                return View(model);
            }
            catch 
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> AllUserCommunities()
        {
            string authorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            var model = await communityService.GetAllUserCommunitiesAsync(authorId);
            return View(model);
        }
    }
}

SimplyForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Simply Forum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimplyForum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Simply Forum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Community" asp-action="All">All communities</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Community" asp-action="AllUserCommunities">My communities</a>
                            </li>
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Add">Add category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Report" asp-action="All">All reports</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="All">All categories</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - SimplyForum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>