SimplyForum/Controllers/CommunityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Community;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class CommunityController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly ICommunityService communityService;
        private readonly IPostService postService;
        private readonly ILikeService likeService;

        public CommunityController(ICategoryService _categoryService,
            ICommunityService _communityService,
            IPostService _postservice,
            ILikeService _likeService)
        {
            categoryService = _categoryService;
            communityService = _communityService;
            postService = _postservice;
            likeService = _likeService;
        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AddCommunityModel()
            {
                CommunityCategories = await categoryService.GetAllCategoriesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCommunityModel model)
        {
            if (await communityService.IsCommunityNameUniqueAsync(model.Name))
            {
                ModelState.AddModelError("Name", "Community name is already used!");
                model.CommunityCategories.AddRange(await categoryService.GetAllCategoriesAsync());
                return View(model);
            }

            if (!ModelState.IsValid) {
                model.CommunityCategories.AddRange(await categoryService.GetAllCategoriesAsync());
                return View(model);
            }

            try
            {
                string authorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

                await communityService.AddCommunityAsync(model, authorId!);
                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Something went wrong!");
                model.CommunityCategories.AddRange(await categoryService.GetAllCategoriesAsync());
                return View(model);
            }
        }


        public async Task<IActionResult> All()
        {
            var model = await communityService.GetAllCommunitiesAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid communityId)
        {
            try
            {
                var model = await communityService.GetCommunityDetailsAsync(communityId);
                model.Posts = await postService.GetAllCommunityPostsAsync(communityId);
                foreach (var post in model.Posts)
                {
                    post.LikeCountModel = await likeService.GetReactionsByPostIdAsync(post.Id);
                }
                return View(model);
            }
            catch 
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> AllUserCommunities()
        {
            string authorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            var model = await communityService.GetAllUserCommunitiesAsync(authorId);
            return View(model);
        }
    }
}

SimplyForum/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Community;
using SimplyForum.Core.Models.Post;
using SimplyForum.Core.Services;
using SimplyForum.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICommentService commentService;
        private readonly ILikeService likeService;
        private readonly IPostReportService postReportService;

        public PostController(IPostService _postService, 
            ICommentService _commentService, 
            ILikeService _likeService,
            IPostReportService _postReportService)
        {
            postService = _postService;
            commentService = _commentService;
            likeService = _likeService;
            postReportService = _postReportService;
        }


        [HttpGet]
        public IActionResult Add(Guid id)
        {
            ViewData["PostType"] = "default";
            var model = new AddPostModel()
            {
                CommunityId = id
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Add(AddPostModel model)
        {
            model.AuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            if (model.Description != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "default";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddDefaultPostAsync(model);
                }
            }
            else if (model.Image != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "image";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddImagePostAsync(model);
                }
            }
            else if (model.Url != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "url";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddUrlPostAsync(model);
                }
            }

            return RedirectToAction("Details", "Community", new { communityId = model.CommunityId });
        }


        public async Task<IActionResult> Details(Guid postId)
        {
            ViewBag.userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            var model = await postService.GetPostDetailsAsync(postId);
            model.LikeCountModel = await likeService.GetReactionsByPostIdAsync(postId);
            model.Comments = await commentService.GetAllPostCommentsAsync(postId);
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid postId, Guid communityId)
        {
            var currentAuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            var actualAuthorId = await postService.GetPostAuthorId(postId);

            if (actualAuthorId != currentAuthorId && !User.IsInRole("Administrator"))
            {
                return Forbid();
            }

            await likeService.DeleteAllPostReactions(postId);
            await commentService.DeleteAllPostComments(postId);
            await postReportService.DeleteAllPostReports(postId);
            await postService.DeletePostAsync(postId);

            return RedirectToAction("Details", "Community", new { communityId = communityId });
        }
    }
}

SimplyForum/Controllers/PostReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.PostReport;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class PostReportController : Controller
    {
        private readonly IPostReportService postReportService;

        public PostReportController(IPostReportService _postReportService)
        {
            postReportService = _postReportService;
        }

        [HttpGet]
        public IActionResult Add(Guid id)
        {
            var model = new AddPostReportModel()
            {
                PostId = id
            };

            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Add(AddPostReportModel model)
        {
            string authorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            model.AuthorId = authorId;

            await postReportService.AddPostReportAsync(model);

            return RedirectToAction("Details", "Post", new { postId = model.PostId });
        }
    }
}

SimplyForum/Controllers/ReactionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class ReactionController : Controller
    {
        private readonly ILikeService likeService;

        public ReactionController(ILikeService _likeService)
        {
            likeService = _likeService;
        }

        public async Task<IActionResult> Like(Guid postId, string returnUrl)
        {
            string userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            await likeService.AddReactionAsync(true, postId, userId);

            return Redirect(returnUrl);
        }

        public async Task<IActionResult> DisLike(Guid postId, string returnUrl)
        {
            string userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            await likeService.AddReactionAsync(false, postId, userId);

            return Redirect(returnUrl);
        }
    }
}

SimplyForum/Views/Community/Add.cshtml
@using SimplyForum.Core.Models.Community
@model AddCommunityModel
@{
    ViewBag.Title = "Add community";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="@Model.Name"></label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true"  placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.BannerImage"></label>
                <input asp-for="@Model.BannerImage" class="form-control" aria-required="true" placeholder="Banner image...">
                <span asp-validation-for="BannerImage" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.CommunityImage"></label>
                <input asp-for="@Model.CommunityImage" class="form-control" aria-required="true" placeholder="Name...">
                <span asp-validation-for="CommunityImage" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.CategoryId">Category</label>
                <select asp-for="@Model.CategoryId" class="form-control">
                    @foreach (var category in Model.CommunityCategories)
                    {
                        <option value="@category.Id">@category.Type</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SimplyForum/Views/Community/All.cshtml
@using SimplyForum.Core.Models.Community
@model IEnumerable<CommunityModel>

@{
    ViewBag.Title = "All communities";
}

@if (Model != null && Model.Any())
{
    <a asp-controller="Community" asp-action="Add" class="btn btn-primary position-absolute top-20 end-10">Add community</a>
    <h2 class="text-center">@ViewBag.Title</h2>
    <hr />
    <ol class="list-group">

        @foreach (var community in Model)
        {
            <li class="list-group-item">
                @{
                    var base64 = Convert.ToBase64String(community.CommunityImage!);
                    var imgSrc = String.Format($"data:image/gif;base64,{base64}");
                }
                <img src="@imgSrc" class="rounded-circle" width="40" height="40" />
                <h1>@community.Name</h1>  
                <h3>@community.CategoryType</h3>
                <form class="input-group-sm" asp-route-communityId="@community.Id" asp-controller="Community" asp-action="Details" method="post">
                    <input type="submit" value="Details" class="fs-6 btn btn-primary mb-3 p-2" />
                </form>
            </li>
        }
    </ol>
}
else{
    <h2 class="text-center">There are no communities yet!</h2>
    <hr />
}

SimplyForum/Views/Community/AllUserCommunities.cshtml
@using SimplyForum.Core.Models.Community
@model IEnumerable<CommunityModel>

@{
    ViewBag.Title = "My communities";
}

@if (Model != null && Model.Any())
{
    <a asp-controller="Community" asp-action="Add" class="btn btn-primary position-absolute top-20 end-10">Add community</a>
    <h2 class="text-center">@ViewBag.Title</h2>
    <hr />
    <ol class="list-group">

        @foreach (var community in Model)
        {
            <li class="list-group-item">
                @{
                    var base64 = Convert.ToBase64String(community.CommunityImage!);
                    var imgSrc = String.Format($"data:image/gif;base64,{base64}");
                }
                <img src="@imgSrc" class="rounded-circle" width="40" height="40" />
                <h1>@community.Name</h1>
            </li>
        }
    </ol>
}
else
{
    <h2 class="text-center">You dont have any communities yet!</h2>
    <hr />
}

SimplyForum/Views/Community/Details.cshtml
@using SimplyForum.Core.Contracts
@using SimplyForum.Core.Models.Community
@using System.Security.Claims
@model CommunityModel

@{
	ViewBag.Title = Model.Name;
}

<div class="text-center container">
    @{
        var base64 = Convert.ToBase64String(Model.BannerImage!);
        var imgSrc = String.Format($"data:image/gif;base64,{base64}");
    }
    <img class="img-fluid" src="@imgSrc" />
    @{
        base64 = Convert.ToBase64String(Model.CommunityImage!);
        imgSrc = String.Format($"data:image/gif;base64,{base64}");
    }
	<img src="@imgSrc" class="rounded-circle" width="80" height="80" />
    <div class="row">
        <h2>@Model.Name</h2>
	    <form asp-controller="Post" asp-action="Add"
	    	  asp-route-id="@Model.Id" method="get">
            <input class="btn btn-primary" type="submit" value="Add post" />
	    </form>
    </div>
    @if (Model.Posts != null && Model.Posts.Any())
    {
        foreach (var post in Model.Posts)
        {
            <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
                <div class="card mt-2 border-primary align-content-center">
                    <div class="card-body">
                        @{
                            base64 = Convert.ToBase64String(post.User.ProfilePicture);
                            imgSrc = String.Format($"data:image/gif;base64,{base64}");
                        }
                        <img src="@imgSrc" class="rounded-circle" width="40" height="40" />
                        <h3>@post.User.UserName</h3>
                        <h5 class="card-title">@post.Title</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@post.CreatedOn</h6>
                        @if (post.Description != null)
                        {
                            <p class="card-text">@post.Description</p>
                        }
                        @if (post.Image != null)
                        {
                            base64 = Convert.ToBase64String(post.Image);
                            imgSrc = String.Format($"data:image/gif;base64,{base64}");
                            <img src="@imgSrc" style="width: 100%;max-height: 100%"/>
                        }
                        @if (post.Url != null)
                        {
                            <a href="@post.Url">@post.Url</a>
                        }
                        <partial name="_PostsReactionsDetailsViewModel" model="post.LikeCountModel" />
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <form class="col" asp-route-postId="@post.Id" asp-controller="Post" asp-action="Details">
                            <input type="submit" value="Details" class="fs-6 btn btn-primary me-1" />
                        </form>
                            <form class="col" asp-route-id="@post.Id" asp-controller="PostReport" asp-action="Add" method="get">
                            <input type="submit" value="Report" class="fs-6 btn btn-secondary me-1" />
                        </form>
                        @if (post.User.Id != null && 
                            post.User.Id == User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value! ||
                            User.IsInRole("Administrator")
                        )
                        {
                                <form class="col" asp-route-postId="@post.Id" asp-route-communityId="@Model.Id" asp-controller="Post" asp-action="Delete">
                            <input type="submit" value="Delete" class="fs-6 btn btn-danger me-1" />
                            </form>
                        }
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <h2 class="text-center">There are no posts yet!</h2>
    }
</div>

@section Scripts{
    <script>
        document.addEventListener("DOMContentLoaded", function (event) {
            var scrollpos = localStorage.getItem('scrollpos');
            if (scrollpos) window.scrollTo({ top: scrollpos, left: 0, behavior: 'smooth' });
        });

        window.onbeforeunload = function (e) {
            localStorage.setItem('scrollpos', window.scrollY);
        };
    </script>
}

SimplyForum/Views/Community/_PostsReactionsDetailsViewModel.cshtml
@using SimplyForum.Core.Models.Like
@using Microsoft.AspNetCore.Http.Extensions
@model LikeCountModel


<a asp-controller="Reaction" asp-action="Like" 
asp-route-postId="@Model.PostId" 
asp-route-returnUrl="@Context.Request.GetEncodedUrl()">
	<i>
		<img src="~/images/like.svg" alt="like" height="35" width="35" />
	</i>
</a>
<span id="reply-likes-@Model.PostId">@Model.Likes</span>
<a asp-controller="Reaction" asp-action="DisLike" 
asp-route-postId="@Model.PostId" 
asp-route-returnUrl="@Context.Request.GetEncodedUrl()">
	<i>
		<img src="~/images/dislike.svg" alt="dislike" height="35" width="35" />
	</i>
</a>
<span id="reply-dislikes-@Model.PostId">@Model.DisLikes</span>