SimplyForum/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Coment;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;

        public CommentController(ICommentService _commentService)
        {
            commentService = _commentService;
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCommentModel model)
        {
            if (ModelState.IsValid)
            {
                string authorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

                await commentService.AddCommentAsync(model, authorId);

            }

            return RedirectToAction("Details", "Post", new { postId = model.PostId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteComment(DeleteCommentModel model)
        {
            var currentAuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            var actualAuthorId = await commentService.GetCommentAuthorId(model.CommentId);

            await commentService.DeleteComment(model.CommentId);

            return RedirectToAction("Details", "Post", new { postId = model.PostId});
        }

    }
}

SimplyForum/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using SimplyForum.Core.Models.Community;
using SimplyForum.Core.Models.Post;
using SimplyForum.Core.Services;
using SimplyForum.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICommentService commentService;
        private readonly ILikeService likeService;
        private readonly IPostReportService postReportService;

        public PostController(IPostService _postService, 
            ICommentService _commentService, 
            ILikeService _likeService,
            IPostReportService _postReportService)
        {
            postService = _postService;
            commentService = _commentService;
            likeService = _likeService;
            postReportService = _postReportService;
        }


        [HttpGet]
        public IActionResult Add(Guid id)
        {
            ViewData["PostType"] = "default";
            var model = new AddPostModel()
            {
                CommunityId = id
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Add(AddPostModel model)
        {
            model.AuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            if (model.Description != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "default";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddDefaultPostAsync(model);
                }
            }
            else if (model.Image != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "image";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddImagePostAsync(model);
                }
            }
            else if (model.Url != null)
            {
                if (!ModelState.IsValid)
                {
                    ViewData["PostType"] = "url";
                    return View(nameof(Add), model);
                }
                else
                {
                    await postService.AddUrlPostAsync(model);
                }
            }

            return RedirectToAction("Details", "Community", new { communityId = model.CommunityId });
        }


        public async Task<IActionResult> Details(Guid postId)
        {
            ViewBag.userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            var model = await postService.GetPostDetailsAsync(postId);
            model.LikeCountModel = await likeService.GetReactionsByPostIdAsync(postId);
            model.Comments = await commentService.GetAllPostCommentsAsync(postId);
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid postId, Guid communityId)
        {
            var currentAuthorId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;
            var actualAuthorId = await postService.GetPostAuthorId(postId);

            if (actualAuthorId != currentAuthorId && !User.IsInRole("Administrator"))
            {
                return Forbid();
            }

            await likeService.DeleteAllPostReactions(postId);
            await commentService.DeleteAllPostComments(postId);
            await postReportService.DeleteAllPostReports(postId);
            await postService.DeletePostAsync(postId);

            return RedirectToAction("Details", "Community", new { communityId = communityId });
        }
    }
}

SimplyForum/Controllers/ReactionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplyForum.Core.Contracts;
using System.Security.Claims;

namespace SimplyForum.Controllers
{
    [Authorize]
    public class ReactionController : Controller
    {
        private readonly ILikeService likeService;

        public ReactionController(ILikeService _likeService)
        {
            likeService = _likeService;
        }

        public async Task<IActionResult> Like(Guid postId, string returnUrl)
        {
            string userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            await likeService.AddReactionAsync(true, postId, userId);

            return Redirect(returnUrl);
        }

        public async Task<IActionResult> DisLike(Guid postId, string returnUrl)
        {
            string userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value!;

            await likeService.AddReactionAsync(false, postId, userId);

            return Redirect(returnUrl);
        }
    }
}

SimplyForum/Views/Post/Add.cshtml
@using SimplyForum.Core.Models.Post
@model AddPostModel

@{
    ViewData["Title"] = "Add Post";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
<div id="tabs">
    <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="default-tab" data-bs-toggle="tab" data-bs-target="#default" role="tab" aria-controls="default" aria-selected="true">Default</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="image-tab" data-bs-toggle="tab" data-bs-target="#image" role="tab" aria-controls="image" aria-selected="false">Image</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="url-tab" data-bs-toggle="tab" data-bs-target="#url" role="tab" aria-controls="url" aria-selected="false">Url</button>
        </li>
    </ul>
</div>
<div class="tab-content">
    <div class="tab-pane" id="default" role="tabpanel" aria-labelledby="default-tab">
        <partial name="_DefaultPost" model="@Model" />
    </div>
    <div class="tab-pane" id="image" role="tabpanel" aria-labelledby="image-tab">
        <partial name="_ImagePost" model="@Model" />
    </div>
    <div class="tab-pane" id="url" role="tabpanel" aria-labelledby="url-tab">
        <partial name="_UrlPost" model="@Model" />
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
     
    <script type="text/javascript">
        var firstTabEl = document.getElementById('@(ViewBag.PostType)-tab');
        var firstTab = new bootstrap.Tab(firstTabEl);
        firstTab.show();
    </script>
}

SimplyForum/Views/Post/Details.cshtml
@using SimplyForum.Core.Models.Coment
@using SimplyForum.Core.Models.Post
@using Microsoft.AspNetCore.Http.Extensions
@model PostModel

@{
	ViewBag.Title = Model.Title;
}

<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
    <div class="card mt-2 border-primary align-content-center">
        <div class="card-body">
            @{
                var base64 = Convert.ToBase64String(Model.User.ProfilePicture);
                var imgSrc = String.Format($"data:image/gif;base64,{base64}");
            }
            <img src="@imgSrc" class="rounded-circle" width="40" height="40" />
            <h3>@Model.User.UserName</h3>
            <h5 class="card-title">@Model.Title</h5>
            <h6 class="card-subtitle mb-2 text-muted">@Model.CreatedOn</h6>
            @if (Model.Description != null)
            {
                <p class="card-text">@Model.Description</p>
            }
            @if (Model.Image != null)
            {
                base64 = Convert.ToBase64String(Model.Image);
                imgSrc = String.Format($"data:image/gif;base64,{base64}");
                <img src="@imgSrc" style="width: 100%;max-height: 100%"/>
            }
            @if (Model.Url != null)
            {
                <a href="@Model.Url">@Model.Url</a>
            }
        </div>

        <div class="card-footer">
            <a asp-controller="Reaction" asp-action="Like"
               asp-route-postId="@Model.LikeCountModel.PostId"
               asp-route-returnUrl="@Context.Request.GetEncodedUrl()">
                <i class="tt-icon">
                    <img src="~/images/like.svg" alt="like" height="35" width="35" />
                </i>
            </a>
            <span id="reply-likes-@Model.LikeCountModel.PostId" class="tt-text">@Model.LikeCountModel.Likes</span>
            <a asp-controller="Reaction" asp-action="DisLike" 
               asp-route-postId="@Model.LikeCountModel.PostId"
               asp-route-returnUrl="@Context.Request.GetEncodedUrl()">
                <i class="tt-icon">
                    <img src="~/images/dislike.svg" alt="dislike" height="35" width="35" />
                </i>
            </a>
            <span id="reply-dislikes-@Model.LikeCountModel.PostId" class="tt-text">@Model.LikeCountModel.DisLikes</span>
        </div>

        <div class="card-body">
            <h5 class="card-title">Add a comment</h5>
            <partial name="_CreateComment" model="new AddCommentModel(){PostId = Model.Id}" />
        </div>
    </div>
</div>
@if (Model.Comments != null && Model.Comments.Any())
{
<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
    <partial name="_CommentsPartialView" model="@Model.Comments" />
</div>
}

<partial name="_CreateReplyModal" model="new AddCommentModel(){PostId = Model.Id}" />
<partial name="_DeleteCommentModal" model="new DeleteCommentModel(){PostId = Model.Id}" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        var replyModal = document.getElementById('replyModal');
        // Send selected comment data to the reply modal.
        replyModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget;
            var commentId = button.getAttribute('data-comment-id');
            replyModal.querySelector('.modal-body #ParentCommentId').value = commentId;
        });

        var deleteModal = document.getElementById('deleteModal');
        // Send selected comment data to the delete modal.
        deleteModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget;
            var commentId = button.getAttribute('data-comment-id');
            deleteModal.querySelector('.modal-body #CommentId').value = commentId;
        });

    </script>

}

SimplyForum/Views/Post/_CommentsPartialView.cshtml
@using SimplyForum.Infrastructure.Data.Models
@model IEnumerable<Comment>

<ul>
    @foreach (var comment in Model)
    {
        <li>
            <div class="card-body">
                @{
                    var base64 = Convert.ToBase64String(comment.Author.ProfilePicture);
                    var imgSrc = String.Format($"data:image/gif;base64,{base64}");
                }
                <img src="@imgSrc" class="rounded-circle" width="40" height="40" />
                <h5 class="card-title">@comment.Author.UserName</h5>
                <h6 class="card-subtitle mb-2 text-muted">@comment.CreatedOn</h6>
                <p class="card-text">@comment.Description</p>                  
                <button type="button" class="btn btn-primary pull-right" data-bs-toggle="modal" data-bs-target="#replyModal"data-comment-id="@comment.Id">Reply</button>
                @if (ViewBag.userId == comment.AuthorId || User.IsInRole("Administrator"))
                {
                <button type="button" class="btn btn-danger pull-right" data-bs-toggle="modal" data-bs-target="#deleteModal" data-comment-id="@comment.Id">Delete</button>
                }
            </div>
            @if (comment.ChildrenComments != null && comment.ChildrenComments.Any()){

                <partial name="_CommentsPartialView" model="comment.ChildrenComments" />
            }
        </li>
    }
</ul>

SimplyForum/Views/Post/_CreateComment.cshtml
@using SimplyForum.Core.Models.Coment
@model AddCommentModel

<form method="post" asp-action="Add" asp-controller="Comment">
    <input type="hidden" asp-for="@Model.PostId" />
    <div class="row">
        <div class="form-group">
            <input asp-for="@Model.Description" class="form-control" aria-required="true" placeholder="Text...">
            <span asp-validation-for="Description" class="small text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col form-group">
            <input type="submit" class="btn btn-success" />
        </div>
    </div>
</form>

SimplyForum/Views/Post/_CreateReplyModal.cshtml
@using SimplyForum.Core.Models.Coment
@model AddCommentModel

<div class="modal fade" id="replyModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="replyModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="replyModalLabel">Reply to this comment ...</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form asp-action="Add" asp-controller="Comment" id="CreateCommentForm">
                        <input type="hidden" asp-for="ParentCommentId"/>
                        <input type="hidden" asp-for="@Model.PostId" />
                        <div class="row mb-3">
                            <div class="col">
                                <div class="form-floating">
                                    <input asp-for="@Model.Description" class="form-control" aria-required="true" placeholder="Text...">
                                    <span asp-validation-for="Description" class="small text-danger"></span>
                                </div>
                            </div>
                        </div>                    
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-outline-primary" value="Send" form="CreateCommentForm">
            </div>
        </div>
    </div>
</div>

SimplyForum/Views/Post/_DefaultPost.cshtml
@using SimplyForum.Core.Models.Post
@model AddPostModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.CommunityId" />
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label">Title</label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label">Description</label>
                <input asp-for="@Model.Description" class="form-control" aria-required="true" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>

SimplyForum/Views/Post/_DeleteCommentModal.cshtml
@using SimplyForum.Core.Models.Coment
@model DeleteCommentModel

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger" id="deleteModalLabel">Delete this comment?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form asp-action="DeleteComment" asp-controller="Comment" id="DeleteCommentForm">
                        <input type="hidden" asp-for="CommentId" />
                        <input type="hidden" asp-for="@Model.PostId" />
                        <div class="row">
                            <div class="col">
                                <p>Are you sure for delete this comment?</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-outline-danger" form="DeleteCommentForm" />
            </div>
        </div>
    </div>
</div>

SimplyForum/Views/Post/_ImagePost.cshtml
@using SimplyForum.Core.Models.Post
@model AddPostModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="@Model.CommunityId" />
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label">Title</label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Image" class="form-label">Image</label>
                <input asp-for="@Model.Image" class="form-control" aria-required="true" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>

SimplyForum/Views/Post/_UrlPost.cshtml
@using SimplyForum.Core.Models.Post
@model AddPostModel

<div class="row tab-pane">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.CommunityId" />
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label">Title</label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Url" class="form-label">Url</label>
                <input asp-for="@Model.Url" class="form-control" aria-required="true" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>